### ISSUE TITLE
Organizing the contents

### ISSUE THREAD

**Issue by RitvikSaranS** [nishant-ai/DSA-Help#132]
@nishant-ai Just a suggestion that instead of putting algorithms and problems in the same folder it would be better to add them in different folders. Like a folder called Sorting, inside it two folders called Algorithms and Problems.

**Comment by iamwatchdogs** [comment]
And also this issue has already been mentioned in the Issues session. You can checkout issue #93.

**Comment by RitvikSaranS** [comment]
@iamwatchdogs I meant in Java section. If that is the intended format then fine. Thanks for the reply :).

**Comment by iamwatchdogs** [comment]
Ohh, I guess that is fixed ( the issue about organizing for the Java directory ). 
but most of them are still uncompilable due to some silly reasons like :
- [ ] not commenting on documentation
- [ ]  Different Class names
- [ ] And adding correct package names *( it's better to package name them if we want to use GitHub Actions )*.

I have fixed those errors in issue #89 by PR #114. Those changes were overridden by other PRs. 
I'm thinking of asking the owner of the Repo to reopen issue #89. What do you say ???...

**Comment by RitvikSaranS** [comment]
@iamwatchdogs Oh should the names of classes and packages should be renamed appropriately to use GitHub actions? I'm sorry to ask this since pretty much a newbie to this. This is about automation, right? Automating the compilation and all? Because then it makes sense that class and package names do matter!!
